const { e } = require("../../../database/emojis.json"),
    { sdb } = require('../../../Routes/functions/database'),
    Moeda = require('../../../Routes/functions/moeda')

module.exports = {
    name: "palavramisturada",
    aliases: ["mix", 'anagrama'],
    category: "game",
    emoji: "🔄",
    usage: "<mix> --- palavra",
    description: "Joguinho da palavra misturada",

    run: async (client, message, args, prefix, db, MessageEmbed, request, sdb) => {

        if (["info", "help", "ajuda"].includes(args[0]?.toLowerCase())) return MixInfo()

        let palavra,
            mixed

        GetAndValidateWord()

        function GetAndValidateWord() {

            palavra = GetWord()
            mixed = Mix(palavra)

            if (palavra == mixed) return GetAndValidateWord()

        }

        let msg = await message.channel.send(`${e.Loading} | Qual é a palavra? **\`${mixed}\`**`),
            control = false,
            collector = message.channel.createMessageCollector({
                filter: m => m.content.toLowerCase() === palavra,
                time: 20000
            })

                .on('collect', m => {

                    control = true

                    sdb.add(`Users.${m.author.id}.Balance`, 150)

                    msg.delete().catch(() => { })
                    message.channel.send(`${e.Check} | ${m.author} acertou a palavra: **\`${mixed}\`** -> **\`${palavra}\`**\n${e.PandaProfit} | +150 ${Moeda(message)}`).catch(() => { })
                    return collector.stop()

                })

                .on('end', () => {

                    if (control) return

                    msg.delete().catch(() => { })
                    return message.channel.send(`${e.Deny} | Ninguém acertou a palavra: **\`${mixed}\`** -> **\`${palavra}\`**`).catch(() => { })

                })

        function MixInfo() {

            return message.reply({
                embeds: [
                    new MessageEmbed()
                        .setColor(client.blue)
                        .setTitle(`🔄 ${client.user.username} Palavras Mixed`)
                        .setDescription('Você é bom em desembaralhar palavras?')
                        .addFields(
                            {
                                name: `${e.Gear} Comando`,
                                value: `\`${prefix}mix\``
                            },
                            {
                                name: `${e.Check} Objetivo`,
                                value: 'Acertar a palavra embaralhada'
                            }
                        )
                ]
            })

        }

    }
}

function Mix(string) {
    // Solution by: Mateus Santos#4492 - 307983856135438337
    return string
        .toLowerCase()
        .split('')
        .sort(() => (0.5 - Math.random()))
        .join('')
}

const Palavras = [

    'não', 'fel', 'paz', 'vil', 'sob', 'ser', 'céu', 'mal', 'ver', 'ter', 'ego', 'bem', 'mãe', 'vão', 'mas', 'vir', 'dar', 'bom', 'ora', 'dom', 'réu', 'são', 'era', 'elo', 'que', 'rol', 'luz', 'tal', 'com', 'nós', 'vis', 'hum', 'até', 'pós', 'seu', 'uma', 'ato', 'foi', 'dia', 'pro', 'dou', 'por', 'pai', 'dor', 'eis', 'sol', 'sem', 'pau', 'irá', 'tez', 'lua', 'ler', 'mim', 'rua', 'tão', 'fiz', 'ajo', 'fim', 'ode', 'lei', 'nem', 'voo', 'dês', 'mau', 'vez', 'mão', 'num', 'meu', 'daí', 'voz', 'gay', 'pôr', 'rio', 'for', 'jus', 'fez', 'afã', 'nau', 'via', 'cia', 'sim', 'ido', 'eco', 'amo', 'rei', 'ira', 'olá', 'tem', 'som', 'lhe', 'uns', 'mês', 'sua', 'clã', 'asa', 'aia', 'lar', 'jaz', 'boa', 'uso',

    'amor', 'fato', 'viés', 'puta', 'mito', 'caos', 'esmo', 'como', 'você', 'brio', 'vide', 'ação', 'após', 'sede', 'pois', 'auge', 'vida', 'ermo', 'ônus', 'saga', 'mote', 'suma', 'tolo', 'idem', 'medo', 'apto', 'crer', 'além', 'urge', 'casa', 'veio', 'vovó', 'foda', 'sina', 'área', 'pude', 'zelo', 'cota', 'ruim', 'coxo', 'soar', 'gozo', 'ente', 'rude', 'ater', 'pela', 'fase', 'rima', 'voga', 'para', 'auto', 'mais', 'tudo', 'será', 'onde', 'cedo', 'cujo', 'trás', 'sela', 'logo', 'meio', 'amar', 'jugo', 'ante', 'teor', 'cela', 'face', 'nojo', 'pose', 'traz', 'numa', 'meta', 'doce', 'arte', 'base', 'asco', 'teve', 'alvo', 'pelo', 'vale', 'agir', 'rito', 'ócio', 'deus', 'alva', 'foco', 'ágil', 'eita', 'todo', 'sair', 'alta', 'nexo', 'alto', 'peço', 'alma', 'tese', 'orla', 'ódio', 'rege', 'mero',

    'sagaz', 'negro', 'âmago', 'mexer', 'êxito', 'termo', 'senso', 'nobre', 'algoz', 'afeto', 'plena', 'ética', 'mútua', 'sutil', 'tênue', 'vigor', 'aquém', 'audaz', 'porém', 'inato', 'sanar', 'seção', 'fazer', 'cerne', 'desde', 'ideia', 'assim', 'moral', 'fosse', 'poder', 'torpe', 'honra', 'muito', 'justo', 'anexo', 'fútil', 'razão', 'gozar', 'ícone', 'quiçá', 'etnia', 'égide', 'sobre', 'tange', 'lapso', 'mútuo', 'expor', 'hábil', 'haver', 'sonho', 'casal', 'amigo', 'posse', 'pesar', 'ávido', 'ardil', 'coser', 'corja', 'tempo', 'genro', 'boçal', 'então', 'detém', 'prole', 'seara', 'causa', 'dengo', 'digno', 'dizer', 'tenaz', 'dever', 'brado', 'ânsia', 'gleba', 'crivo', 'óbice', 'ápice', 'saber', 'ceder', 'ânimo', 'pária', 'atroz', 'assaz', 'comum', 'culto', 'temor', 'censo', 'sendo', 'graça', 'denso', 'mundo', 'cozer', 'fugaz', 'pauta', 'valha', 'porra', 'orgia', 'neném', 'vício', 'ainda',

    'exceto', 'cínico', 'idôneo', 'âmbito', 'néscio', 'mister', 'índole', 'apogeu', 'vereda', 'inócuo', 'convém', 'utopia', 'sádico', 'ênfase', 'escopo', 'mérito', 'alusão', 'casual', 'anseio', 'pressa', 'alheio', 'hostil', 'nocivo', 'idiota', 'infame', 'legado', 'gentil', 'cético', 'exímio', 'afável', 'adorno', 'hétero', 'clichê', 'boceta', 'paixão', 'adesão', 'dádiva', 'sóbrio', 'êxtase', 'astuto', 'aferir', 'otário', 'limiar', 'solene', 'formal', 'sessão', 'apreço', 'lábaro', 'difuso', 'julgar', 'ocioso', 'hábito', 'ensejo', 'outrem', 'eficaz', 'júbilo', 'safado', 'larica', 'também', 'ímpeto', 'alento', 'embora', 'glória', 'dispor', 'facção', 'escusa', 'exílio', 'perene', 'abster', 'lúdico', 'cessão', 'alçada', 'nuance', 'ilação', 'acento', 'isento', 'objeto', 'etéreo', 'acesso', 'cortês', 'tácito', 'sisudo', 'eximir', 'sanção', 'cobiça', 'axioma', 'receio', 'mazela', 'remoto', 'avidez', 'vulgar', 'buscar', 'desejo', 'fático', 'asseio', 'cômico', 'ciente', 'adágio', 'alocar', 'prazer',

    'empatia', 'embuste', 'cônjuge', 'exceção', 'efêmero', 'prolixo', 'caráter', 'idílico', 'verbete', 'análogo', 'genuíno', 'sublime', 'estória', 'pêsames', 'sucinto', 'inferir', 'apático', 'audácia', 'família', 'acepção', 'astúcia', 'pródigo', 'recesso', 'redimir', 'estigma', 'estável', 'refutar', 'cinismo', 'cultura', 'virtude', 'exortar', 'icônico', 'mórbido', 'cordial', 'trivial', 'soberba', 'escória', 'síntese', 'aspecto', 'imputar', 'emergir', 'mitigar', 'anátema', 'luxúria', 'deboche', 'candura', 'almejar', 'alegria', 'excerto', 'ademais', 'sucesso', 'frívolo', 'litígio', 'através', 'oriundo', 'contudo', 'austero', 'sensato', 'caralho', 'estrupo', 'alcunha', 'fomento', 'excesso', 'ambíguo', 'salutar', 'quimera', 'conciso', 'ambição', 'ninfeta', 'orgulho', 'parcial', 'imersão', 'coragem', 'modesto', 'relação', 'isenção', 'exilado', 'exótico', 'notório', 'padecer', 'erudito', 'colosso', 'demanda', 'auferir', 'ansioso', 'déspota', 'colapso', 'volátil', 'difusão', 'estirpe', 'inércia', 'intenso', 'saudade', 'emotivo', 'vigente', 'límpido', 'escroto', 'profano', 'amizade', 'piedade',

    'inerente', 'peculiar', 'denegrir', 'genocida', 'respeito', 'anuência', 'deferido', 'prudente', 'equidade', 'iminente', 'pandemia', 'invasivo', 'essência', 'alienado', 'desgraça', 'misógino', 'eminente', 'extensão', 'abstrato', 'empírico', 'premissa', 'conceito', 'ardiloso', 'reiterar', 'ascensão', 'passível', 'prodígio', 'devaneio', 'lascívia', 'conserto', 'talarico', 'relativo', 'modéstia', 'apologia', 'analogia', 'inserção', 'ativista', 'inóspito', 'monótono', 'respaldo', 'remissão', 'sinônimo', 'medíocre', 'concerne', 'despeito', 'alicerce', 'retórica', 'rapariga', 'destarte', 'rechaçar', 'gratidão', 'fomentar', 'proceder', 'notívago', 'demagogo', 'primazia', 'metódico', 'consiste', 'distinto', 'abnegado', 'critério', 'elegível', 'desfecho', 'portanto', 'suscitar', 'perfídia', 'complexo', 'sucumbir', 'singular', 'escárnio', 'amálgama', 'paradoxo', 'vocábulo', 'história', 'inefável', 'jurídico', 'espectro', 'verídico', 'desígnio', 'instigar', 'processo', 'obstante', 'contexto', 'solícito', 'sanidade', 'impávido', 'refletir', 'resoluto', 'maestria', 'insípido', 'expedido', 'paralelo', 'comunhão', 'repudiar', 'objetivo', 'imanente', 'emulação', 'prosaico', 'problema', 'presteza',

    'perspicaz', 'recíproco', 'impressão', 'concessão', 'supérfluo', 'escrúpulo', 'retificar', 'presunção', 'paradigma', 'concepção', 'implícito', 'dicotomia', 'hipócrita', 'plenitude', 'essencial', 'propósito', 'hegemonia', 'ratificar', 'corolário', 'incidente', 'esdrúxulo', 'hermético', 'persuadir', 'vagabundo', 'deliberar', 'aleatório', 'promíscuo', 'altruísmo', 'sapiência', 'esperança', 'altruísta', 'demasiado', 'indelével', 'resignado', 'mesquinho', 'confiança', 'eminência', 'regozijar', 'impetuoso', 'descrição', 'inusitado', 'diligente', 'compaixão', 'analítico', 'pretensão', 'prudência', 'exequível', 'desdenhar', 'explícito', 'discrição', 'autóctone', 'dissensão', 'fidedigno', 'constante', 'ordinário', 'companhia', 'taciturno', 'autêntico', 'supressão', 'resolução', 'percepção', 'nostalgia', 'expressão', 'subjetivo', 'restrição', 'execrável', 'imparcial', 'discorrer', 'adjacente', 'autonomia', 'jactância', 'instância', 'sintético', 'interesse', 'iminência', 'obstinado', 'limítrofe', 'presságio', 'arrogante', 'cognitivo', 'irascível', 'consoante', 'outrossim', 'ludibriar', 'desumilde', 'ignorante', 'estagnado', 'eloquente', 'relevante', 'paciência', 'aquisição', 'pederasta', 'leniência', 'vagabunda', 'empecilho', 'convicção', 'ambicioso', 'magnânimo', 'suplantar', 'pretérito',

    'dicionário', 'prescindir', 'intrínseco', 'presunçoso', 'diligência', 'corroborar', 'intempérie', 'detrimento', 'parcimônia', 'maturidade', 'referência', 'inspiração', 'inexorável', 'incipiente', 'prepotente', 'sororidade', 'pragmático', 'indulgente', 'arbitrário', 'serenidade', 'disruptivo', 'sagacidade', 'auspicioso', 'iniquidade', 'pertinente', 'preconizar', 'resignação', 'vislumbrar', 'precedente', 'incidência', 'subestimar', 'disposição', 'depreender', 'suscetível', 'lisonjeado', 'preliminar', 'hipocrisia', 'entretanto', 'excêntrico', 'equivocado', 'tribulação', 'retrógrado', 'anacrônico', 'indolência', 'ingerência', 'escrutínio', 'infortúnio', 'excelência', 'contemplar', 'restringir', 'compassivo', 'sintetizar', 'fleumático', 'coercitivo', 'signatário', 'importante', 'democracia', 'pejorativo', 'primordial', 'proposição', 'conjuntura', 'pecuniária', 'finalidade', 'espontâneo', 'dissolução', 'esplêndido', 'designação', 'transeunte', 'itinerário', 'subjacente', 'alteridade', 'no entanto', 'desprovido', 'necessário', 'intrínseca', 'pernóstico', 'masoquista', 'divergente', 'sarcástico', 'privilégio', 'verossímil', 'exacerbado', 'pernicioso', 'disseminar', 'relevância', 'pusilânime', 'militância', 'inferência', 'meticuloso', 'constância', 'idoneidade', 'esporádico', 'morosidade', 'consolidar', 'estupefato', 'satisfação', 'disciplina', 'excludente', 'subversivo', 'distinguir',

    'significado', 'perspectiva', 'resiliência', 'dissimulado', 'vicissitude', 'complacente', 'peremptório', 'contundente', 'compreensão', 'comorbidade', 'perspicácia', 'expectativa', 'beneplácito', 'subterfúgio', 'pressuposto', 'indiferente', 'preconceito', 'pretensioso', 'beligerante', 'consonância', 'imensurável', 'transcender', 'contingente', 'intensidade', 'proeminente', 'superficial', 'inenarrável', 'contencioso', 'concernente', 'necessidade', 'animosidade', 'experiência', 'benignidade', 'antagonismo', 'incumbência', 'vocabulário', 'intervenção', 'reivindicar', 'cumprimento', 'indiferença', 'supracitado', 'compreender', 'resistência', 'deliberação', 'estereótipo', 'especulação', 'proveniente', 'elucubração', 'ambiguidade', 'divergência', 'indubitável', 'subsequente', 'diversidade', 'prognóstico', 'benevolente', 'indulgência', 'redundância', 'tergiversar', 'heterogêneo', 'integridade', 'displicente', 'importância', 'oportunista', 'conveniente', 'identificar', 'estabelecer', 'austeridade', 'substantivo', 'congruência', 'providência', 'discriminar', 'negligência', 'conferência', 'admoestação', 'verborragia', 'compulsório', 'generalizar', 'excepcional', 'facultativo', 'sistemático', 'consciência', 'pragmatismo', 'subordinado', 'intersecção', 'intelectual', 'contradição', 'comprimento', 'desenvolver', 'substancial', 'melancólico', 'determinado', 'procedência', 'consecutivo', 'autoritário', 'retificação', 'conservador', 'dificuldade', 'desprezível', 'enfermidade', 'relativizar',

    'perseverança', 'condolências', 'remanescente', 'ninfomaníaca', 'prerrogativa', 'extrovertido', 'complacência', 'procrastinar', 'discrepância', 'independente', 'determinação', 'consequência', 'intermitente', 'conveniência', 'benevolência', 'eclesiástico', 'felicitações', 'contingência', 'compartilhar', 'transgressão', 'consideração', 'convergência', 'cordialidade', 'não obstante', 'concomitante', 'disseminação', 'subsistência', 'convencional', 'conhecimento', 'cumplicidade', 'sistematizar', 'complexidade', 'prescindível', 'proselitismo', 'controvérsia', 'impertinente', 'imprevisível', 'inverossímil', 'displicência', 'interlocutor', 'coincidência', 'extemporâneo', 'libertinagem', 'maledicência', 'resplandecer', 'proporcionar', 'conformidade', 'intolerância', 'intempestivo', 'escatológico', 'fraternidade', 'estabilidade', 'mediocridade', 'perseverante', 'misericórdia', 'coexistência', 'persistência', 'parcialmente', 'preeminência', 'consolidação', 'introvertido', 'complementar', 'protagonista', 'circunspecto', 'aquiescência', 'estigmatizar', 'maquiavélico', 'hermenêutica', 'proeminência', 'destinatário', 'deslumbrante', 'caracterizar', 'superestimar', 'constituição', 'enclausurado', 'oportunidade', 'consistência', 'interessante', 'parcialidade', 'condicionado', 'procedimento', 'entendimento', 'incircunciso', 'escarnecedor', 'fragmentação', 'generosidade', 'legitimidade', 'depreciativo', 'ininterrupto', 'desenvoltura', 'proficiência', 'literalmente', 'incolumidade', 'racionalizar', 'circuncidado', 'sobremaneira', 'ninfomaníaco', 'perplexidade', 'constrangido', 'beneficência',

    'reciprocidade', 'contemporâneo', 'inconveniente', 'circunstância', 'discernimento', 'solidariedade', 'promiscuidade', 'heterossexual', 'intransigente', 'aprovisionado', 'credibilidade', 'transcendente', 'discriminação', 'contrapartida', 'epistemologia', 'assintomático', 'perpendicular', 'comprobatório', 'ressignificar', 'ressentimento', 'estereotipado', 'reminiscência', 'incongruência', 'recenseamento', 'possibilidade', 'intermediário', 'indispensável', 'preponderante', 'veementemente', 'pormenorizado', 'subjetividade', 'longanimidade', 'singularidade', 'hodiernamente', 'subserviência', 'incontinência', 'convalescença', 'superveniente', 'autenticidade', 'instabilidade', 'reivindicação', 'transformação', 'elegibilidade', 'sensibilidade', 'latifundiário', 'independência', 'indissociável', 'multifacetado', 'contraditório', 'superestimado', 'recalcitrante', 'introspectivo', 'eventualmente', 'incredulidade', 'desmistificar', 'inconsequente', 'ininteligível', 'sobressalente', 'quintessência', 'inescrupuloso', 'integralmente', 'indescritível', 'comportamento', 'homogeneidade', 'magnificência', 'a despeito de', 'provavelmente', 'precipuamente', 'circunscrição', 'personalidade', 'remanejamento', 'peculiaridade', 'implementação', 'convalescente', 'consciencioso', 'consentimento', 'arrefecimento', 'correlacionar', 'filho pródigo', 'contentamento', 'incandescente', 'predisposição', 'incondicional', 'serendipidade', 'monossilábico', 'versatilidade', 'conscientizar', 'indeterminado', 'desnecessário', 'especificação', 'imperceptível', 'irresponsável', 'supersticioso', 'tergiversação', 'ressarcimento', 'reconciliação', 'representação', 'receptividade', 'incognoscível', 'identificação',

    'imprescindível', 'condescendente', 'característica', 'idiossincrasia', 'concupiscência', 'extraordinário', 'demasiadamente', 'intercorrência', 'irrepreensível', 'consubstanciar', 'incomensurável', 'preponderância', 'arbitrariedade', 'discricionário', 'especificidade', 'posteriormente', 'pronta-entrega', 'imprescritível', 'intransponível', 'contextualizar', 'sadomasoquismo', 'empreendimento', 'entretenimento', 'revolucionário', 'superveniência', 'ancestralidade', 'infraestrutura', 'paulatinamente', 'transcendental', 'atenciosamente', 'periodicamente', 'bem-aventurado', 'relacionamento', 'transcendência', 'democratização', 'ponto de vista', 'arrependimento', 'imparcialidade', 'reconhecimento', 'diligentemente', 'insignificante', 'personificação', 'espontaneidade', 'inconsistência', 'despretensioso', 'impessoalidade', 'intransigência', 'socioambiental', 'aplicabilidade', 'cônjuge virago', 'procrastinador', 'desprendimento', 'trazer à baila', 'principalmente', 'prestatividade', 'potencialidade', 'excentricidade', 'congratulações', 'funcionalidade', 'licenciosidade', 'pusilanimidade', 'inconveniência', 'estratificação', 'exequibilidade', 'insubstituível', 'procrastinação', 'credenciamento', 'resplandecente', 'dissolutamente', 'coercitividade', 'abundantemente', 'extraordinária', 'plausibilidade', 'internalização', 'jurisprudência', 'biodiversidade', 'epistemológico', 'multiplicidade', 'implicitamente', 'disponibilizar', 'individualismo', 'acessibilidade', 'aleatoriamente', 'constantemente', 'exclusivamente', 'estelionatário', 'perfeccionista', 'impressionante', 'questionamento', 'grandiloquente', 'intermunicipal', 'esclarecimento', 'minuciosamente', 'menção honrosa', 'indiscriminado', 'frequentemente', 'semianalfabeto', 'sobrecarregado', 'concessionária', 'reestruturação',

    'amor', 'anuência', 'análogo', 'alienado', 'apogeu', 'abstrato', 'ardiloso', 'apático', 'ascensão', 'arbitrário', 'audácia', 'acepção', 'auspicioso', 'astúcia', 'algoz', 'aleatório', 'altruísmo', 'afeto', 'altruísta', 'apologia', 'analogia', 'ativista', 'alusão', 'anseio', 'alicerce', 'alheio', 'aspecto', 'analítico', 'abnegado', 'afável', 'autóctone', 'anátema', 'anacrônico', 'adorno', 'animosidade', 'amálgama', 'aquém', 'audaz', 'antagonismo', 'almejar', 'autêntico', 'adesão', 'alegria', 'ademais', 'através', 'assim', 'astuto', 'aferir', 'austero', 'adjacente', 'autonomia', 'alcunha', 'apreço', 'abstrair', 'ambíguo', 'ambição', 'arrogante', 'ação', 'alento', 'anexo', 'alteridade', 'aquisição', 'após', 'aprovisionado', 'auferir', 'ambicioso', 'ansioso', 'abster', 'ambiguidade', 'arcabouço', 'arquétipo', 'amizade', 'analisar', 'auge', 'alçada', 'alienação', 'assento', 'acento', 'alegoria', 'arraigado', 'apetecer', 'assintomático', 'atenuar', 'altivez', 'assunção', 'acesso', 'austeridade', 'atípico', 'atemporal', 'abominável', 'afeição', 'axioma', 'admoestar', 'apreciação', 'amigo', 'avidez', 'admoestação', 'anomalia', 'ausência', 'arrojado',

    'beneplácito', 'beligerante', 'benevolência', 'benignidade', 'boceta', 'brio', 'bizarro', 'benevolente', 'bem', 'basculho', 'buscar', 'boçal', 'balbúrdia', 'brado', 'bíblia', 'bélico', 'bastardo', 'bom', 'benefício', 'bordão', 'brando', 'banal', 'blasfêmia', 'balbuciar', 'bruma', 'beleza', 'base', 'baluarte', 'brasileiro', 'benigno', 'batráquio', 'bravo', 'beneficência', 'burro', 'bálsamo', 'barganha', 'butique', 'beldade', 'bucólico', 'bênção', 'bojo', 'brega', 'bajulador', 'benesse', 'bondade', 'bárbaro', 'bem-aventurado', 'benemérito', 'bonito', 'belicoso', 'brasil', 'binômio', 'botar', 'brevidade', 'bochecha', 'bravata', 'bonança', 'belo', 'beata', 'birra', 'breve', 'balizar', 'brisa', 'boemia', 'bilateral', 'branda', 'bullying', 'burocracia', 'banalizar', 'banzo', 'bêbado', 'bastante', 'blasé', 'buço', 'bolo', 'bom senso', 'basilar', 'bando', 'banzeiro', 'burocrático', 'burrice', 'boutique', 'brava', 'bola', 'bilíngue', 'bajular', 'bruços', 'brecha', 'brincar', 'brincadeira', 'babaca', 'brandura', 'bem - vindo', 'biltre', 'bençãos', 'bondoso', 'bem-sucedido', 'bem-estar', 'beligerância', 'biodiversidade',

    'cônjuge', 'condescendente', 'cínico', 'concessão', 'corroborar', 'condolências', 'caráter', 'contemporâneo', 'concepção', 'complacente', 'corolário', 'complacência', 'contundente', 'característica', 'convém', 'condescendência', 'conceito', 'compreensão', 'comorbidade', 'concupiscência', 'conserto', 'circunstância', 'cinismo', 'confiança', 'consequência', 'cultura', 'casual', 'conveniência', 'concerne', 'cordial', 'caos', 'consonância', 'compaixão', 'consiste', 'cético', 'contingente', 'critério', 'complexo', 'contencioso', 'concernente', 'contingência', 'compartilhar', 'clichê', 'candura', 'como', 'constante', 'companhia', 'contemplar', 'compassivo', 'contexto', 'cerne', 'coercitivo', 'comunhão', 'contudo', 'consideração', 'cumprimento', 'caralho', 'conjuntura', 'convergência', 'compreender', 'céu', 'cordialidade', 'conciso', 'cognitivo', 'carência', 'consoante', 'concomitante', 'custódia', 'coragem', 'contenda', 'convencional', 'concerto', 'colosso', 'conhecimento', 'convicção', 'conceder', 'colapso', 'credibilidade', 'cessão', 'cumplicidade', 'condição', 'coerente', 'concisão', 'complexidade', 'contíguo', 'ciência', 'constância', 'contrapartida', 'canalha', 'concomitantemente', 'contenção', 'coadunar', 'controvérsia', 'caridade', 'consolidar', 'conveniente', 'conhecer', 'coerência', 'cortês', 'congruência',

    'dicionário', 'denegrir', 'dissimulado', 'diligência', 'deferido', 'detrimento', 'dicotomia', 'desgraça', 'discrepância', 'disruptivo', 'devaneio', 'deliberar', 'determinação', 'demasiado', 'discernimento', 'descrição', 'despeito', 'diligente', 'destarte', 'disposição', 'dê', 'depreender', 'demagogo', 'demasiadamente', 'distinto', 'desdenhar', 'discrição', 'desfecho', 'deboche', 'dissensão', 'dádiva', 'desígnio', 'desde', 'discorrer', 'democracia', 'desenvolvimento', 'dissolução', 'difuso', 'designação', 'disseminação', 'dimensão', 'desumilde', 'deliberação', 'dispor', 'demanda', 'desprovido', 'déspota', 'difusão', 'divergência', 'divergente', 'diversidade', 'dinâmico', 'disseminar', 'discriminação', 'deleitar', 'displicente', 'diferença', 'disciplina', 'definir', 'displicência', 'distinguir', 'discriminar', 'deleite', 'destreza', 'dinamismo', 'devasso', 'dispêndio', 'desprezo', 'desejo', 'desgraçado', 'deveras', 'deferir', 'distinção', 'dignidade', 'detém', 'diferente', 'doutrina', 'desafio', 'dengo', 'digno', 'dizer', 'difícil', 'disperso', 'declínio', 'dever', 'dirimir', 'descrever', 'diante', 'deferência', 'discussão', 'deturpado', 'diferir', 'dúvida', 'debalde', 'desenvolver', 'debochado', 'danado', 'determinado', 'despojar', 'desídia',

    'empatia', 'embuste', 'exceção', 'efêmero', 'exceto', 'escrúpulo', 'equidade', 'estória', 'essência', 'extrovertido', 'essencial', 'eminente', 'extensão', 'empírico', 'esdrúxulo', 'encarecidamente', 'extraordinário', 'expectativa', 'esperança', 'estigma', 'estável', 'escopo', 'eminência', 'exortar', 'escória', 'emergir', 'eclesiástico', 'entretanto', 'excêntrico', 'exequível', 'explícito', 'equivocado', 'exímio', 'elegível', 'esmo', 'escárnio', 'experiência', 'escrutínio', 'excelência', 'excerto', 'expressão', 'espectro', 'execrável', 'expedido', 'emulação', 'estrupo', 'excesso', 'espontâneo', 'esplêndido', 'ensejo', 'eficaz', 'epifania', 'endêmico', 'estúpido', 'exilado', 'estagnado', 'eloquente', 'exótico', 'embora', 'erudito', 'estereótipo', 'especulação', 'escusa', 'empecilho', 'enxergar', 'exílio', 'elucubração', 'estirpe', 'excelente', 'excitado', 'entediado', 'emotivo', 'etnia', 'exacerbado', 'escroto', 'excedente', 'enfadonho', 'exortação', 'escrever', 'epistemologia', 'ego', 'esporádico', 'estupefato', 'empáfia', 'expor', 'estabelecer', 'etéreo', 'ermo', 'excludente', 'eximir', 'escasso', 'espairecer', 'emergente', 'etimologia', 'elucidar', 'efeminado', 'espúrio', 'estereotipado', 'extasiado', 'excepcional',

    'fato', 'família', 'fomentar', 'felicitações', 'fel', 'fidedigno', 'fazer', 'frívolo', 'fleumático', 'fosse', 'fomento', 'formal', 'finalidade', 'fulguras', 'facção', 'fútil', 'felicidade', 'fundamento', 'fático', 'facultativo', 'fé', 'formidável', 'factível', 'filantropo', 'fortuito', 'fraternidade', 'faceta', 'foda', 'formoso', 'formos', 'fugaz', 'flâmula', 'fenômeno', 'facínora', 'forte', 'franco', 'frivolidade', 'fruição', 'fase', 'fanfarrão', 'fatídico', 'facultado', 'fidelidade', 'fidalgo', 'fornicação', 'flexível', 'fluir', 'fúlgido', 'falar', 'forma', 'feliz', 'feição', 'florão', 'flagelo', 'face', 'fascismo', 'florescer', 'forjar', 'fragmentação', 'façanha', 'fetiche', 'fluxo', 'frisar', 'fálico', 'frugal', 'favorável', 'famigerado', 'favor', 'foco', 'função', 'fundamental', 'fizesse', 'fulcral', 'fácil', 'filosofia', 'furtivo', 'fator', 'façam', 'falso', 'farsa', 'falange', 'faccioso', 'fictício', 'falácia', 'falta', 'fulgor', 'fragmentado', 'fardo', 'forasteiro', 'fariseu', 'força', 'frívola', 'fértil', 'feixe', 'fascinante', 'fora', 'felicitação', 'foi', 'fraude', 'fragrância',

    'genocida', 'genuíno', 'gratidão', 'gentil', 'genérico', 'glória', 'gozar', 'generoso', 'generalizar', 'genro', 'gleba', 'graça', 'garrida', 'grotesco', 'gozo', 'grande', 'ganância', 'gênese', 'garboso', 'guisa', 'gênero', 'genioso', 'gerar', 'generosidade', 'gregário', 'genocídio', 'garbo', 'galgar', 'grato', 'gentileza', 'geração', 'gente', 'gesto', 'gratificante', 'gambito', 'gênio', 'galanteador', 'gratuito', 'gentalha', 'gestão', 'gama', 'gostoso', 'guarida', 'genealogia', 'guardar', 'gradual', 'grau', 'gramática', 'galhardia', 'garantir', 'guia', 'galardoador', 'gaiato', 'gerir', 'grafar', 'genitor', 'grupo', 'grosso', 'gradativo', 'genitora', 'generalizado', 'gigolô', 'gay', 'glossário', 'gostar', 'gana', 'grátis', 'grave', 'girassol', 'grilhões', 'granjear', 'galardão', 'galante', 'glosa', 'guardião', 'guarda', 'grata', 'glutonaria', 'guerra', 'geografia', 'grandeza', 'grandiloquente', 'globalização', 'gracejo', 'glutão', 'gato', 'garatuja', 'germinar', 'guilda', 'genuinamente', 'gata borralheira', 'grotão', 'gradação', 'grandemente', 'gracioso', 'geral', 'ganhar', 'gosto', 'generalização', 'grosseria',

    'hipócrita', 'hegemonia', 'hermético', 'heterogeneidade', 'hostil', 'hipocrisia', 'hétero', 'história', 'heterossexual', 'hábito', 'honra', 'hesitar', 'harmonia', 'híbrido', 'humildade', 'heterogêneo', 'hábil', 'haver', 'holístico', 'homogêneo', 'hipótese', 'hipotético', 'honestidade', 'herege', 'hierarquia', 'hodiernamente', 'hodierno', 'hermenêutica', 'habilidade', 'hedonismo', 'homem', 'hipoteticamente', 'humilde', 'heresia', 'hostilizar', 'herói', 'havia', 'histérica', 'hilário', 'humanidade', 'histriônico', 'homônimo', 'hum', 'hereditário', 'hombridade', 'honorário', 'hostilidade', 'honesto', 'haste', 'herético', 'homossexual', 'honorários', 'homogeneidade', 'humor', 'hiato', 'horda', 'hera', 'haja', 'higidez', 'hidrópico', 'honorífico', 'hediondo', 'há', 'heurístico', 'humano', 'hoje', 'houve', 'hesitação', 'homofobia', 'homologar', 'habitar', 'honrado', 'hierárquico', 'histórico', 'homenagem', 'hardcore', 'humilhar', 'hein', 'honrar', 'horizonte', 'homologação', 'holocausto', 'hiperbólico', 'hercúleo', 'heroico', 'homicida', 'harmonioso', 'hipérbole', 'homólogo', 'hortifrúti', 'habitual', 'hipossuficiente', 'higienizar', 'histeria', 'hosana', 'hesitante', 'hegemônico', 'higiene', 'hecatombe', 'humilhação',

    'imprescindível', 'inerente', 'intrínseco', 'impressão', 'intempérie', 'idôneo', 'idílico', 'iminente', 'implícito', 'invasivo', 'inconveniente', 'inspiração', 'inócuo', 'inexorável', 'incidente', 'incipiente', 'idiossincrasia', 'inferir', 'intrinsecamente', 'indulgente', 'independente', 'iniquidade', 'indelével', 'inserção', 'inóspito', 'intermitente', 'incidência', 'impetuoso', 'icônico', 'indiferente', 'inusitado', 'idiota', 'infame', 'imputar', 'imensurável', 'intensidade', 'inenarrável', 'indolência', 'inefável', 'ingerência', 'inato', 'infortúnio', 'incumbência', 'instigar', 'imparcial', 'impávido', 'intervenção', 'ideia', 'insípido', 'importante', 'imanente', 'indiferença', 'instância', 'interesse', 'iminência', 'irascível', 'incrível', 'imersão', 'itinerário', 'isenção', 'ignorante', 'intransigente', 'inércia', 'intenso', 'insólito', 'incólume', 'intrínseca', 'indubitável', 'intenção', 'insensato', 'indulgência', 'imponente', 'ilação', 'indagar', 'inferência', 'incisivo', 'idoneidade', 'indivíduo', 'interação', 'isento', 'integridade', 'importância', 'intuito', 'incauto', 'indolente', 'inspirar', 'ignóbil', 'incógnita', 'impertinente', 'imprevisível', 'identificar', 'inverossímil', 'insolente', 'interlocutor', 'influência', 'impacto', 'intercorrência', 'idem', 'irrepreensível', 'instável',

    'jurídico', 'jactância', 'julgar', 'júbilo', 'justo', 'justiça', 'jeito', 'juízo', 'jugo', 'jamais', 'já', 'justificar', 'joia', 'jovial', 'jovem', 'justaposição', 'jurista', 'junto', 'jazia', 'jocoso', 'jiboia', 'jornada', 'jargão', 'jurisprudência', 'jus', 'jardim', 'juiz', 'jubileu', 'julgamento', 'joio', 'junco', 'jirau', 'jaguara', 'jurisdição', 'junção', 'judeu', 'jactancioso', 'janota', 'jaz', 'juntar', 'justificativa', 'jagunço', 'jubilar', 'juntamente', 'jactar', 'jejum', 'jazigo', 'jiló', 'já', 'já', 'jovialidade', 'jaez', 'jogar', 'justaposto', 'jubiloso', 'jazer', 'juvenil', 'jubilado', 'justa', 'jogo', 'jornal', 'jaja', 'júlia', 'jurisdicionado', 'juventude', 'janela', 'justificação', 'jurisdicional', 'jerimum', 'jeová', 'judicioso', 'juízo de valor', 'jenipapo', 'jeitoso', 'jabá', 'junta', 'justapor', 'jacaré', 'justamente', 'jazida mineral', 'jusante', 'judicial', 'jurisconsulto', 'jipe', 'joelho', 'jorrar', 'jegue', 'jabuti', 'jóquei', 'juridicamente', 'joaninha', 'jeca', 'jurar', 'jia', 'jornaleiro', 'justificado', 'júnior', 'juro', 'judiação', 'jantar', 'jesuíta',

    'kit', 'ketchup', 'kamikaze', 'kiwi', 'karaokê', 'kaiser', 'kilo', 'kilo', 'kg', 'km', 'kung fu', 'kitsch', 'kelvin', 'krill', 'keep calm', 'kantiano', 'kyrie', 'kartódromo', 'keynesianismo', 'klaxon', 'kebab', 'kantismo', 'kibutz', 'kichute', 'kilt', 'kantista', 'kepleriano', 'knob', 'kalio', 'keynesiano', 'kcal', 'kartista', 'káon', 'kimberlito', 'kummel', 'kirsch', 'kartismo', 'kb', 'kaiserismo', 'kaiserista', 'kneippismo', 'kilobit', 'krausismo', 'kneippista', 'kansa', 'kieserita',

    'lascívia', 'lisonjeado', 'legado', 'luxúria', 'litígio', 'limiar', 'lábaro', 'limítrofe', 'larica', 'ludibriar', 'leniência', 'lúdico', 'límpido', 'liberdade', 'lapso', 'lascivo', 'leviano', 'libertinagem', 'lealdade', 'lírico', 'linear', 'logradouro', 'lograr', 'locatário', 'lunático', 'latente', 'lactante', 'lúgubre', 'letárgico', 'longânimo', 'lúcido', 'lícito', 'locupletar', 'lacuna', 'letargia', 'longevidade', 'longanimidade', 'louco', 'lavrar', 'limite', 'logo', 'latifundiário', 'luz', 'luzindo', 'lavrador', 'limbo', 'lugar', 'léxico', 'lástima', 'legitimidade', 'laico', 'literalmente', 'lânguido', 'lembrança', 'limosidade', 'lucidez', 'levar', 'lastro', 'longitudinal', 'lavra', 'legal', 'labor', 'leviandade', 'leigo', 'lambisgoia', 'ladino', 'latifúndio', 'lazarento', 'lume', 'leito', 'loquaz', 'lisonja', 'labuta', 'litigante', 'libidinoso', 'linda', 'lua', 'literal', 'ler', 'legenda', 'luta', 'lamúria', 'líder', 'língua', 'lesado', 'lazer', 'lancinante', 'lamento', 'ludibriado', 'longínquo', 'lembrar', 'liame', 'lotado', 'leviana', 'lapidar', 'litigar', 'liturgia', 'lisura', 'lei', 'livro',

    'maturidade', 'mister', 'misógino', 'mexer', 'mito', 'modéstia', 'mesquinho', 'mérito', 'monótono', 'medíocre', 'mórbido', 'mútua', 'metódico', 'mitigar', 'maestria', 'moral', 'mediante', 'mal', 'molestar', 'modesto', 'muito', 'magnânimo', 'masoquista', 'magnífico', 'militância', 'mancebo', 'meticuloso', 'mútuo', 'morosidade', 'mãe', 'mazela', 'mote', 'miserável', 'moribundo', 'medo', 'moleque', 'metáfora', 'moléstia', 'maledicência', 'mas', 'mentecapto', 'melancólico', 'mesquinhez', 'mundo', 'minucioso', 'mediocridade', 'mormente', 'maroto', 'misericórdia', 'menção', 'meretriz', 'martírio', 'melindre', 'método', 'mostrar', 'magnitude', 'mudança', 'modalidade', 'mutuamente', 'maravilhoso', 'mais', 'mercenário', 'melhor', 'maquiavélico', 'mensurável', 'manso', 'mulher', 'mercê', 'ministrar', 'mitigação', 'manancial', 'meio', 'meiga', 'metamorfose', 'multifacetado', 'momento', 'melindroso', 'mártir', 'mobilidade', 'melindrosa', 'mágoa', 'mesmo', 'menosprezar', 'meta', 'matiz', 'metódica', 'melancolia', 'marasmo', 'matilha', 'maleável', 'maçante', 'missão', 'monopólio', 'monotonia', 'martirizar', 'mobilizador', 'mítico', 'macambúzio', 'moderado', 'mediador',

    'ninfomaníaca', 'néscio', 'negro', 'nobre', 'notívago', 'nocivo', 'não', 'necessidade', 'nostalgia', 'não obstante', 'ninfeta', 'notório', 'no entanto', 'necessário', 'nuance', 'negligência', 'neófito', 'nômade', 'natureza', 'nevrálgico', 'neném', 'nativo', 'nefasto', 'nojo', 'numa', 'nós', 'nexo', 'ninfomaníaco', 'negligenciar', 'noção', 'noia', 'nicho', 'novo', 'nosocômio', 'nobreza', 'natural', 'notável', 'nomenclatura', 'ninguém', 'noite', 'nítido', 'nada', 'nome', 'nominal', 'naturalidade', 'nó', 'nórdico', 'nato', 'nortear', 'negligente', 'necrofilia', 'nenhuma', 'nem', 'nostálgico', 'nossa', 'nunca', 'num', 'nude', 'nojento', 'nação', 'norma', 'nascer', 'nuança', 'nódoa', 'nulípara', 'nefelibata', 'normativo', 'nível', 'nacionalidade', 'neologismo', 'namorar', 'niilismo', 'navio', 'normal', 'neutro', 'núcleo', 'narrativa', 'nefasta', 'nau', 'negócio', 'nuances', 'notícia', 'naquele', 'nostálgica', 'noutro', 'nipônico', 'nazismo', 'naquela', 'nepotismo', 'negrito', 'novidade', 'norteador', 'necessitar', 'nitidez', 'núpcias', 'neo', 'nos', 'número', 'nosologia', 'néctar',

    'ordinário', 'obstante', 'oriundo', 'objetivo', 'otário', 'obstinado', 'ocioso', 'outrem', 'orgulho', 'outrossim', 'ousadia', 'opróbrio', 'oportunista', 'objeto', 'oblíquo', 'olvidar', 'orgânico', 'outorgar', 'obséquio', 'opinião', 'obsoleto', 'onírico', 'obsceno', 'origem', 'orgia', 'objeção', 'ora', 'ortodoxo', 'outrora', 'ordem', 'ociosidade', 'ontológico', 'observar', 'oportuno', 'obsessão', 'onde', 'ontem', 'oposição', 'orgulhoso', 'ojeriza', 'opressor', 'oportunidade', 'obter', 'ontologia', 'obstinação', 'ostracismo', 'omissão', 'opulência', 'oneroso', 'organização', 'omitir', 'olhar', 'orla', 'obcecado', 'opressão', 'otimizar', 'ousado', 'oblação', 'outorgado', 'onerar', 'ouvir', 'orientação', 'ostensivo', 'ocorrência', 'ofuscar', 'obtuso', 'oligarquia', 'obedecer', 'ofício', 'outro', 'obtenção', 'original', 'onanismo', 'obstar', 'ofensa', 'ostentação', 'orgasmo', 'otimista', 'omisso', 'orientar', 'oposto', 'obrigado', 'obstáculo', 'obrigação', 'ostentas', 'opor', 'ordinária', 'obscuro', 'opulento', 'obliterar', 'ode', 'oráculo', 'obstruir', 'obstrução', 'oponível', 'ocasião', 'ocaso', 'oferecer', 'opção', 'onipotente',

    'perseverança', 'perspicaz', 'peculiar', 'perspectiva', 'prescindir', 'presunçoso', 'prolixo', 'prudente', 'presunção', 'paradigma', 'prerrogativa', 'pandemia', 'parcimônia', 'plenitude', 'propósito', 'puta', 'pêsames', 'peremptório', 'premissa', 'procrastinar', 'prepotente', 'pragmático', 'perspicácia', 'passível', 'prodígio', 'persuadir', 'pródigo', 'promíscuo', 'plena', 'pertinente', 'preconizar', 'pressuposto', 'precedente', 'preconceito', 'pretensioso', 'pressa', 'proceder', 'preliminar', 'primazia', 'pretensão', 'promiscuidade', 'prudência', 'portanto', 'perfídia', 'proeminente', 'paradoxo', 'porém', 'paixão', 'paz', 'percepção', 'processo', 'paralelo', 'poder', 'prosaico', 'problema', 'pejorativo', 'primordial', 'proposição', 'pecuniária', 'presteza', 'prendado', 'presságio', 'preceder', 'preceito', 'parcial', 'paciência', 'padecer', 'perverso', 'pederasta', 'proveniente', 'perplexo', 'ponderar', 'pretérito', 'plausível', 'perene', 'preâmbulo', 'pernóstico', 'privilégio', 'pois', 'profano', 'pernicioso', 'piedade', 'prognóstico', 'primícias', 'pusilânime', 'promover', 'prescindível', 'pleitear', 'proselitismo', 'precisão', 'provérbio', 'preciso', 'profícuo', 'provisão', 'perpendicular', 'parâmetro', 'providência', 'plácidas', 'posterior', 'postergar',

    'quimera', 'quiçá', 'qualidade', 'quesito', 'quando', 'que', 'quinhão', 'quanto', 'qualitativo', 'questão', 'qualquer', 'quarentena', 'querela', 'quintessência', 'querer', 'quão', 'quer', 'quiser', 'quilombo', 'quaisquer', 'quenga', 'qual', 'querido', 'quota', 'quase', 'quis', 'queijo', 'quem', 'questionar', 'questionamento', 'quantidade', 'quimérico', 'queixa', 'quadrilha', 'quitute', 'quisesse', 'quiescente', 'qualificar', 'quantitativo', 'queira', 'queima-roupa', 'quociente', 'querência', 'quieto', 'quadro', 'quinquilharia', 'querida', 'quarteirão', 'queixo', 'quisera', 'quiz', 'quixotesco', 'quente', 'qualificação', 'qualificado', 'quilombola', 'quietude', 'quite', 'queda', 'quartel', 'quebrantado', 'quebrar', 'quantas', 'queixar', 'quais', 'quantum', 'quebranto', 'quotidiano', 'quitanda', 'quedar', 'quinquênio', 'quantificar', 'quitação', 'quadra', 'quê', 'quatorze', 'quebrantar', 'quilograma', 'quadrúpede', 'querigma', 'quinhentos', 'quebrado', 'quiabo', 'querelante', 'quieta', 'quitar', 'queixume', 'quorum', 'queto', 'quiropata', 'questiúncula', 'quilo', 'química', 'quitinete', 'quadrante', 'quebra-cabeça', 'quarto', 'quisto', 'quebra', 'quengo',

    'respeito', 'recíproco', 'resiliência', 'reciprocidade', 'remanescente', 'retificar', 'ratificar', 'referência', 'reiterar', 'recesso', 'relativo', 'redimir', 'refutar', 'resignação', 'resignado', 'respaldo', 'regozijar', 'remissão', 'retórica', 'rapariga', 'rechaçar', 'retrógrado', 'resolução', 'restringir', 'restrição', 'refletir', 'resoluto', 'repudiar', 'reivindicar', 'redenção', 'relação', 'reflexão', 'resistência', 'relevante', 'responsabilidade', 'razão', 'recíproca', 'relevância', 'redundância', 'racismo', 'revogado', 'reverberar', 'renunciar', 'ridículo', 'ressignificar', 'receio', 'remoto', 'ressentimento', 'revogar', 'retumbante', 'reminiscência', 'resplandecer', 'retaliação', 'realizar', 'resquício', 'ressaltar', 'rancor', 'retidão', 'relutante', 'recenseamento', 'requerente', 'retificação', 'ressalva', 'resiliente', 'regular', 'racional', 'redarguir', 'respectivo', 'rotina', 'relativizar', 'reputação', 'retroativo', 'réplica', 'retenção', 'redundante', 'ruim', 'respectivamente', 'relacionar', 'revés', 'reportar', 'rude', 'regra', 'referente', 'receoso', 'remeter', 'refúgio', 'religião', 'recôndito', 'reaça', 'réu', 'rima', 'refratário', 'recrudescer', 'reparar', 'repúdio', 'round', 'restrito', 'radical', 'recorrente', 'réprobo',

    'significado', 'supérfluo', 'sagaz', 'sublime', 'sucinto', 'sororidade', 'serenidade', 'sádico', 'senso', 'sagacidade', 'sapiência', 'subterfúgio', 'subestimar', 'sinônimo', 'simultaneamente', 'soberba', 'solidariedade', 'suscetível', 'síntese', 'sutil', 'suscitar', 'superficial', 'sucumbir', 'singular', 'supressão', 'sanar', 'seção', 'sob', 'sucesso', 'subjetivo', 'sintetizar', 'sóbrio', 'solícito', 'sanidade', 'signatário', 'ser', 'sensato', 'solene', 'sessão', 'supracitado', 'salutar', 'sintético', 'safado', 'subsistência', 'subjacente', 'subjugar', 'subsídio', 'suplantar', 'saudade', 'salientar', 'subsequente', 'sarcástico', 'sede', 'sistematizar', 'submisso', 'sórdido', 'sentido', 'sufrágio', 'sobre', 'submissão', 'soberano', 'satisfação', 'suprimir', 'situação', 'segmento', 'substantivo', 'subversivo', 'sonho', 'sisudo', 'sanção', 'saga', 'submeter', 'suma', 'saudosista', 'supremacia', 'singelo', 'sistemático', 'seara', 'sarcasmo', 'subordinado', 'solidário', 'sensatez', 'sentimento', 'sutileza', 'sancionar', 'saber', 'seriedade', 'sempre', 'subsistir', 'substancial', 'soberbo', 'solitude', 'sensível', 'sendo', 'sina', 'serelepe', 'sedentário', 'simplório', 'símbolo', 'soar',

    'termo', 'talarico', 'trivial', 'transcender', 'tribulação', 'tênue', 'transgressão', 'taciturno', 'torpe', 'transeunte', 'também', 'transcendente', 'tange', 'tergiversar', 'ter', 'tendência', 'tácito', 'tangível', 'trabalho', 'tolo', 'tempo', 'todavia', 'tenaz', 'tráfego', 'temor', 'transição', 'talento', 'tácita', 'temerário', 'tolerância', 'tenro', 'tirano', 'tenacidade', 'transar', 'ternura', 'transmutar', 'tudo', 'trouxa', 'transformação', 'teoria', 'trás', 'tranquilo', 'temperança', 'trazer', 'temer', 'tópico', 'transgredir', 'tecnologia', 'teor', 'tendencioso', 'translúcido', 'traz', 'transversal', 'tal', 'tríade', 'teve', 'tipificar', 'torpeza', 'tornar', 'tédio', 'tinhoso', 'tomar', 'típico', 'talvez', 'triste', 'tratativa', 'tragédia', 'todo', 'tempestivo', 'tecer', 'todos', 'traduzir', 'tese', 'tesão', 'tensão', 'transcrever', 'tratar', 'tristeza', 'trouxe', 'transpor', 'translado', 'tendo', 'tráfico', 'tímido', 'transcendental', 'terminologia', 'toada', 'tende', 'titubear', 'transformar', 'transitório', 'terno', 'tradição', 'trivialidade', 'terrível', 'torpor', 'transcendência', 'tema', 'tóxico', 'tolher',

    'utopia', 'urge', 'usufruir', 'ufanismo', 'usura', 'ulterior', 'universo', 'um', 'unânime', 'urbanidade', 'união', 'utilizar', 'uma', 'usurpador', 'uma vez que', 'unguento', 'unilateral', 'unidade', 'uníssono', 'ultraje', 'usurpar', 'urbano', 'utensílio', 'ubíquo', 'ufanar', 'unívoco', 'umbral', 'usar', 'unicidade', 'utópico', 'universal', 'uniformidade', 'ubiquidade', 'ultrajado', 'urdidura', 'unificado', 'unidade federativa', 'urgia', 'unanimidade', 'ufanista', 'urgente', 'uniforme', 'uns', 'ultrajante', 'unificar', 'utilizado', 'uso', 'usuário', 'unissex', 'urgência', 'usurpação', 'usurpadora', 'uau', 'urdir', 'ultrapassar', 'ufano', 'ufa', 'ululante', 'utilidade', 'ultimato', 'unir', 'ultra', 'unigênito', 'urgir', 'usual', 'usufrutuário', 'urbe', 'untar', 'ungido', 'uno', 'ultrajar', 'universalidade', 'urdido', 'ultimamente', 'utilitarismo', 'usurário', 'utilitário', 'ungir', 'unção', 'umidade', 'uniformemente', 'unitário', 'utilização', 'univocidade', 'urubu', 'usucapião', 'utente', 'unicórnio', 'unificação', 'ultrapassado', 'uva', 'uni', 'urgentemente', 'usufruto', 'untuoso', 'urze', 'urbanização', 'unidirecional', 'urucubaca', 'unanimemente',

    'verbete', 'vicissitude', 'viés', 'vereda', 'vagabundo', 'vislumbrar', 'virtude', 'vigor', 'vocábulo', 'você', 'vil', 'verídico', 'vocabulário', 'vide', 'versátil', 'ver', 'vertente', 'vigoroso', 'vagabunda', 'volátil', 'vigente', 'verossímil', 'veemente', 'verossimilhança', 'veemência', 'vida', 'volúpia', 'vitupério', 'vulgar', 'varonil', 'volúvel', 'verborragia', 'vedado', 'vão', 'vir', 'vice-versa', 'veio', 'vovó', 'valha', 'ventura', 'verdade', 'vício', 'vigência', 'vulnerável', 'veementemente', 'vulgo', 'vaidade', 'vertiginoso', 'venham', 'voga', 'viril', 'veredito', 'viagem', 'veracidade', 'vendo', 'vó', 'vermos', 'visar', 'vosmecê', 'vestígio', 'virtuoso', 'valor', 'vênia', 'vitalidade', 'visceral', 'vale', 'vital', 'vivaz', 'valia', 'visão', 'vetado', 'vínculo', 'verificar', 'vontade', 'vis', 'virtual', 'vilipendiado', 'vitimismo', 'várias', 'virtuosa', 'viver', 'violência', 'vassalo', 'vemos', 'vocação', 'vangloriar', 'viável', 'vácuo', 'vadia', 'viabilizar', 'varão', 'velho', 'vernáculo', 'volitivo', 'voluptuoso', 'volatilidade', 'voltar', 'vergonha', 'venerar', 'virgem',

    'web', 'workshop', 'watt', 'walkman', 'winchester', 'wc', 'workaholic', 'weltanschauung', 'walter', 'warrant', 'www', 'web design', 'wu', 'weber', 'western', 'wagneriano', 'warrantagem', 'whig', 'weberiano', 'windsurfe', 'wi-fi', 'wattímetro', 'wagnerismo', 'wildiano', 'warrantar', 'wulfenita', 'wurtzita', 'warrantado', 'wagnerita', 'wagnerista', 'windsurfista', 'wollastonita', 'wronskiano',

    'xenofobia', 'xibiu', 'xingar', 'xeque', 'xícara', 'xale', 'xará', 'xerife', 'xenofóbico', 'xodó', 'xaveco', 'xucro', 'xadrez', 'xibungo', 'xampu', 'xá', 'xexo', 'xepa', 'xenófobo', 'xixi', 'xereta', 'xácara', 'xilogravura', 'xarope', 'xereca', 'xexelento', 'xingamento', 'xifópago', 'xaxado', 'xenofobismo', 'xiita', 'xingo', 'xaxim', 'xiquexique', 'xote', 'xisto', 'xeque-mate', 'xinxim', 'xoxota', 'xilindró', 'xerox', 'xupé', 'xavante', 'xenofilia', 'xero', 'xota', 'xilofone', 'xeretar', 'xerém', 'xuá', 'ximbica', 'xilografia', 'xamã', 'xexéu', 'xeique', 'xilo', 'xi', 'xaréu', 'xoxo', 'xerocar', 'xamânico', 'xereré', 'xibio', 'xis', 'xelim', 'xilopódio', 'xexeiro', 'xangô', 'xotar', 'xororó', 'xerez', 'xô', 'xiri', 'xérox', 'xerófilo', 'xifoide', 'xamanismo', 'xilófilo', 'xistoso', 'xarada', 'xavecar', 'xexé', 'xerocópia', 'xavier', 'xintoísmo', 'xadrezista', 'xerostomia', 'xixixi', 'xepeiro', 'xilógrafo', 'xenófilo', 'xilema', 'xuxo', 'xerodermia', 'xofrango', 'xacra', 'xaropear', 'xerocopiar', 'xantocrômico',

    'yakisoba', 'yang', 'yogurt', 'yin-yang', 'yuppie', 'yagi', 'yin', 'yakuza',

    'zelo', 'zombar', 'zelar', 'zeloso', 'zoológico', 'zangado', 'zumbi', 'zombeteiro', 'zorra', 'zoofilia', 'zoeira', 'zoar', 'zombaria', 'zen', 'zênite', 'zona', 'zoada', 'zoomórfico', 'zero', 'zebra', 'zíper', 'ziquizira', 'zombador', 'zumbido', 'zoom', 'zunir', 'zarolho', 'zarpar', 'zodíaco', 'zigoto', 'zéfiro', 'zelador', 'zoólogo', 'zangar', 'ziguezague', 'zonzo', 'zumbir', 'zangão', 'zica', 'zoologia', 'zunido', 'zanga', 'zabelê', 'zircão', 'zoonótico', 'zoo', 'zurrar', 'zigurate', 'zoonose', 'zimbo', 'zebu', 'zeugma', 'zona tropical', 'zoomorfismo', 'zaino', 'zimbro', 'zanzar', 'zurro', 'zurzir', 'zaragatoa', 'zagaia', 'zapear', 'zabumba', 'zônula', 'zimbório', 'zepelim', 'zaragata', 'zerar', 'zelote', 'zurrapa', 'zureta', 'zerado', 'zilhão', 'zum', 'zoófito', 'zarabatana', 'zoofílico', 'zinco', 'zambujeiro', 'zorô', 'zagueiro', 'zoneamento', 'zinabre', 'zulu', 'zoófilo', 'zesto', 'zetética', 'zootecnia', 'zaga', 'zeladoria', 'zoomorfia', 'zeta', 'zorro', 'zape', 'zagal', 'zinho', 'zetético', 'zoofagia', 'zambelê'
]

function GetWord() {
    return Palavras[Math.floor(Math.random() * Palavras.length)]
}